# SPDX-FileCopyrightText: 2026 Mattia Egloff <mattia.egloff@pm.me>
#
# SPDX-License-Identifier: GPL-3.0-or-later

# WinUI spells this public API type "WriteableBitmap".
[default.extend-identifiers]
WriteableBitmap = "WriteableBitmap"
