// Auto-generated by scripts/generate.py — do not edit
// SPDX-FileCopyrightText: 2026 Mattia Egloff <mattia.egloff@pm.me>
// SPDX-License-Identifier: GPL-3.0-or-later

namespace Vauchi.UI;

/// <summary>Design tokens generated from tokens.json.</summary>
public static class Tokens
{
    public static class Spacing
    {
        public const double Xs = 4;
        public const double Sm = 8;
        public const double Md = 16;
        public const double Lg = 24;
        public const double Xl = 32;
    }
    public static class SpacingDirection
    {
        public const double ContentStart = 16;
        public const double ContentEnd = 16;
        public const double ListItemStart = 8;
        public const double ListItemEnd = 8;
        public const double ListItemInlineStart = 12;
        public const double ListItemInlineEnd = 12;
    }
    public static class Typography
    {
        public const double TitleSize = 24;
        public const double SubtitleSize = 18;
        public const double BodySize = 16;
        public const double CaptionSize = 14;
    }
    public static class BorderRadius
    {
        public const double Sm = 4;
        public const double Md = 8;
        public const double MdLg = 12;
        public const double Lg = 16;
    }
    public static class TouchTarget
    {
        public const double Minimum = 44;
    }
    public static class Motion
    {
        public const double EnterDurationMs = 200;
        public const double ExitDurationMs = 150;
        public const double EmphasisDurationMs = 300;
    }
}
